# Generated by Django 5.0.3 on 2024-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formhandlers', '0002_booknow'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='sex',
            field=models.CharField(default='Not specified', max_length=10),
        ),
    ]
