# Generated by Django 5.0.3 on 2024-03-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formhandlers', '0005_alter_patientinfo_blood_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='sex',
        ),
    ]
